name: ci

on:
  push:
    branches:
      - '**'
    tags: ['v*.*.*']
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies 📦
        run: yarn install --immutable
      - name: Run build
        run: yarn run build

  docker:
    uses: reims2/actions/.github/workflows/docker.yml@main
    concurrency: docker-${{ github.ref }}
    if: ${{ github.event_name != 'merge_group' }}
    secrets: inherit # pass all secrets

  deploy:
    needs:
      - docker
    if: github.ref == 'refs/heads/main'
    uses: reims2/actions/.github/workflows/deploy.yml@main
    concurrency: deploy-${{ github.repository }}
    secrets: inherit # pass all secrets

  dev-deploy:
    needs:
      - docker
    if: github.event_name == 'workflow_dispatch'
    uses: reims2/actions/.github/workflows/dev-deploy.yml@main
    concurrency: dev-deploy-${{ github.repository }}
    secrets: inherit # pass all secrets
